add_newline = true

[package]
symbol = ""

[git_branch]
symbol = " "

[git_status]
style = "bold purple"

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'
vimcmd_symbol = '[<](bold fg:green)'
vimcmd_replace_one_symbol = '[<](bold fg:color_purple)'
vimcmd_replace_symbol = '[<](bold fg:color_purple)'
vimcmd_visual_symbol = '[<](bold fg:color_yellow)'

[gcloud]
disabled = true

[aws]
disabled = false
style = 'bold yellow'
symbol = ' '
format = 'using [$symbol($profile )(\[$duration\] )]($style)'

[ruby]
disabled = true

[python]
symbol = ' '
style = 'bold blue'

[lua]
disabled = true

[docker_context]
disabled = true

[golang]
format = '[ $version ](bold blue)'
